building:
  image: node:12
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    expire_in: 3 days
    paths:
      - dist

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - rm -rf public/*
    - mv dist/* public
  artifacts:
    expire_in: 3 days
    paths:
      - public
  only:
    - main